// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/vvika/OneDrive/Desktop/LowLevelDesign/url_shortner/controller/url_controller.go

// Package mocks is a generated GoMock package.
package mocks
