// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/vvika/OneDrive/Desktop/LowLevelDesign/url_shortner/services/url_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vvikash157/url_shortener/models"
)

// MockURLService is a mock of URLService interface.
type MockURLService struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceMockRecorder
}

// MockURLServiceMockRecorder is the mock recorder for MockURLService.
type MockURLServiceMockRecorder struct {
	mock *MockURLService
}

// NewMockURLService creates a new mock instance.
func NewMockURLService(ctrl *gomock.Controller) *MockURLService {
	mock := &MockURLService{ctrl: ctrl}
	mock.recorder = &MockURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLService) EXPECT() *MockURLServiceMockRecorder {
	return m.recorder
}

// ResolveUrl mocks base method.
func (m *MockURLService) ResolveUrl(code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUrl", code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUrl indicates an expected call of ResolveUrl.
func (mr *MockURLServiceMockRecorder) ResolveUrl(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUrl", reflect.TypeOf((*MockURLService)(nil).ResolveUrl), code)
}

// UrlShortener mocks base method.
func (m *MockURLService) UrlShortener(request models.ShortenRequest) (models.ShortenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UrlShortener", request)
	ret0, _ := ret[0].(models.ShortenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UrlShortener indicates an expected call of UrlShortener.
func (mr *MockURLServiceMockRecorder) UrlShortener(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UrlShortener", reflect.TypeOf((*MockURLService)(nil).UrlShortener), request)
}
